### ISSUE TITLE
Circle in middle of clock

### ISSUE THREAD

**Issue by KaterinaSlezakova** [KaterinaSlezakova/clock-javascript#1]
I would apprecciate any help to find out how can I move little circle exactly in middle of clock. Problem is probably somewhere in CSS but don't have any clue what to change. Thank you 😊

**Comment by Dyios** [comment]
Hi, yes the problem is in the CSS at line 91 there is a "," missing between the two values.
"transform: translate(-50% -50%);" should be "transform: translate(-50%, -50%);"

**Comment by KaterinaSlezakova** [comment]
> Hi, yes the problem is in the CSS at line 91 there is a "," missing between the two values.
> "transform: translate(-50% -50%);" should be "transform: translate(-50%, -50%);"

Thank you it fixed the issue 👍
